version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 1972
      - 45773:52773
      - 53773
    volumes:
      - ./:/irisrun/repo
    hostname: caserver

  client:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 46773:52773
    volumes:
      - ./:/irisrun/repo
    hostname: caclient
  